FROM oven/bun:1-alpine
RUN apk update && apk add --no-cache tzdata

# Bun install cache
ENV BUN_INSTALL_CACHE_DIR=/bun-cache
RUN mkdir -p $BUN_INSTALL_CACHE_DIR && chown -R bun:bun $BUN_INSTALL_CACHE_DIR

# Docker Entry Point
COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

RUN mkdir -p /logs
