FROM oven/bun:1-alpine

# Add bash
RUN apk add --no-cache bash

# Bun install cache
ENV BUN_INSTALL_CACHE_DIR=/bun-cache
RUN mkdir -p $BUN_INSTALL_CACHE_DIR

# Docker Entry Point
COPY ./deploy/startup-dev.sh /
RUN chmod +x /startup-dev.sh

# Env Loader
COPY ./deploy/loadEnv.sh /
RUN chmod +x /loadEnv.sh

ENTRYPOINT ["/startup-dev.sh"]
